web_server:
  bind: 0.0.0.0
  port: 3539

schedules:
  - tasks: [ pterclub, totheglory, rss_download, manage_conn ]
    interval:
      minutes: 1

  - tasks: [ reseed, resume, delete, modify, clean ]
    interval:
      minutes: 5

  - tasks: [ opencd, springsunday, dmhy ]
    interval:
      minutes: 10

  - tasks: [ sign_in, warner ]
    schedule:
      minute: 30
      hour: 8-23

variables:
  headers:
    user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36'
  via: &via_setting
    - wecom:
        corp_id: 'xxxxxxxx'
        corp_secret: 'xxxxxxxx'
        agent_id: 'xxxxxxxx'
        to_user: 'xxxxxxxx'
    - telegram:
        bot_token: 'xxxxxxxx'
        recipients:
          - username: 'xxxxxxxx'

templates:
  from_qbittorrent_template:
    from_qbittorrent_mod: &qbittorrent_setting
      host: qbittorrent.example.com
      port: 443
      use_ssl: yes
      username: xxxxxxxx
      password: xxxxxxxx

  qbittorrent_base_template:
    qbittorrent_mod: *qbittorrent_setting

  qbittorrent_add_template:
    qbittorrent_mod:
      action:
        add:
          reject_on:
            bandwidth_limit: 13107200
            dl_speed: 0.6
            dl_limit: 8388608
          category: Rss
          autoTMM: yes

  qbittorrent_resume_template:
    qbittorrent_mod:
      action:
        resume:
          recheck_torrents: yes

  qbittorrent_pause_template:
    qbittorrent_mod:
      action:
        pause: yes

  qbittorrent_manage_conn_template:
    qbittorrent_mod:
      action:
        manage_conn:
          min: 100
          max: 2000

  qbittorrent_delete_keeper_template:
    qbittorrent_mod:
      action:
        remove:
          keeper:
            check_reseed:
              - chdbits
              - totheglory
              - m-team
              - open
              - pterclub
              - springsunday
              - ourbits
              - hdsky
              - keepfrds
              - tjupt
              - skyey2
              - dmhy
            delete_files: yes
            keep_disk_space: 10
            dl_limit_on_succeeded: 0
            alt_dl_limit_on_succeeded: 8388608
            dl_limit_interval: 1800

  qbittorrent_delete_cleaner_template:
    qbittorrent_mod:
      action:
        remove:
          cleaner:
            delete_files: yes

  qbittorrent_modify_template:
    qbittorrent_mod:
      action:
        modify:
          tag_by_tracker: yes
          replace_trackers:
            'http://tracker.pterclub.com/announce?passkey=xxxxxxxx': 'https://tracker.pterclub.com/announce?passkey=xxxxxxxx'

  show_entry_template:
    show_entry:
      state: accepted
      attribute: yes

tasks:
  pterclub:
    rss:
      url: https://pterclub.com/torrentrss.php?rows=10&cat413=1&tag_internal=yes&isize=1&linktype=dl&passkey=xxxxxxxx
      all_entries: no
      other_fields:
        - link
    no_entries_ok: yes
    if:
      - size > 1024 * 1024 and size < 20 * 1024 *1024: accept
    notify:
      entries:
        message: "Title: {{title}}\nLink: {{link}}"
        via: *via_setting
    qbittorrent_mod:
      action:
        add:
          category: PTer
          reject_on:
            dl_speed: no
            dl_limit: no
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template

  totheglory:
    rss:
      url: https://totheglory.im/putrss.php?par=xxxxxxxx==&ssl=yes
      all_entries: no
    no_entries_ok: yes
    limit_new: 1
    regexp:
      accept:
        - TTG
        - Wiki
      from: title
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template

  springsunday:
    html_rss:
      url: https://springsunday.net/torrents.php?incldead=0&spstate=4&pick=0&inclbookmarked=0&exclusive=0&search=&search_area=0&search_mode=0&sort=8&type=desc
      headers:
        cookie: 'xxxxxxxx'
        user-agent: '{? headers.user_agent ?}'
      params: '&passkey=xxxxxxxx'
      root_element_selector: '.torrents > tbody > tr:not(:first-child)'
      fields:
        title:
          element_selector: 'a[href*="details.php"]'
          attribute: title
        url:
          element_selector: 'a[href*="download.php"]'
          attribute: href
        promotion:
          element_selector: '.pro_free2up'
          attribute: alt
        seeders:
          element_selector: 'td:nth-child(7)'
          attribute: textContent
        leechers:
          element_selector: 'td:nth-child(8)'
          attribute: textContent
    no_entries_ok: yes
    limit_new: 1
    if:
      - leechers|int > 30 and seeders|int >0 and seeders|int < 3 and promotion: accept
    qbittorrent_mod:
      action:
        add:
          reject_on:
            dl_speed: 0.8
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template
      #- show_entry_template

  opencd:
    html_rss:
      url: https://open.cd/torrents.php?spstate=2&seeders=3&sort=7&type=asc
      headers:
        cookie: 'xxxxxxxx'
        user-agent: '{? headers.user_agent ?}'
      params: '&passkey=xxxxxxxx'
      root_element_selector: '#form_torrent > table > tbody > tr:not(:first-child)'
      fields:
        title:
          element_selector: 'a[href*="details.php"]'
          attribute: title
        url:
          element_selector: 'a[href*="download.php"]'
          attribute: href
        promotion:
          element_selector: 'div[style="padding-bottom: 5px"] > img'
          attribute: alt
        progress:
          element_selector: '.progress_completed'
          attribute: class
    no_entries_ok: yes
    limit_new: 1
    if:
      - promotion in ['Free', '2X Free']: accept
      - "progress and 'progress_completed' not in progress": reject
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template

  dmhy:
    html_rss:
      url: https://u2.dmhy.org/torrents.php?sort=8&type=desc
      headers:
        cookie: 'xxxxxxxx'
        user-agent: '{? headers.user_agent ?}'
      params: '&passkey=xxxxxxxx'
      root_element_selector: '#outer > table.main > tbody > tr > td > table > tbody > tr:not(:first-child)'
      fields:
        title:
          element_selector: 'a[href*="details.php"]'
          attribute: textContent
        url:
          element_selector: 'a[href*="download.php"]'
          attribute: href
        promotion:
          element_selector: 'img[class*="pro"]'
          attribute: alt
        promotion_time:
          element_selector: 'b > time'
          attribute: title
        upload_ratio:
          element_selector: 'img[alt="上传比率"] + b'
          attribute: textContent
        download_ratio:
          element_selector: 'img[alt="下载比率"] + b'
          attribute: textContent
        seeders:
          element_selector: 'td:nth-child(6)'
          attribute: textContent
        leechers:
          element_selector: 'td:nth-child(7) > b'
          attribute: textContent
    no_entries_ok: yes
    limit_new: 1
    if:
      - promotion_time and promotion_time|parsedate < now + timedelta(hours=12): reject
      - upload_ratio == '2.33X' and download_ratio == '0.00X' and leechers|int > 10 and seeders|int >0 and seeders|int < 3: accept
      - promotion in ['2X Free'] and leechers|int > 10 and seeders|int >0 and seeders|int < 3: accept
    qbittorrent_mod:
      action:
        add:
          reject_on:
            dl_speed: no
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template
      #- show_entry_template

  gazellegames:
    html_rss:
      url: https://gazellegames.net/torrents.php?order_way=desc&order_by=leechers&artistname=&action=advanced&groupname=&year=&remastertitle=&remasteryear=&releasetitle=&releasegroup=&filelist=&sizesmall=&sizelarge=&userrating=&metarating=&ignrating=&gsrating=&encoding=&format=&region=&language=&rating=&miscellaneous=&scene=&dupable=&freetorrent=1&gamedox=&gamedoxvers=&taglist=&tags_type=1&empty_groups=both
      headers:
        cookie: 'xxxxxxxx'
        user-agent: '{? headers.user_agent ?}'
      root_element_selector: 'tr[class*=edition_]'
      fields:
        title:
          element_selector: 'span[title]'
          attribute: textContent
        url:
          element_selector: 'a[title="Download"]'
          attribute: href
        promotion:
          element_selector: '.freeleech_label'
          attribute: textContent
        seeders:
          element_selector: 'td:nth-child(6)'
          attribute: textContent
        leechers:
          element_selector: 'td:nth-child(7)'
          attribute: textContent
        progress:
          element_selector: '.progress_completed'
          attribute: class
    no_entries_ok: yes
    limit_new: 1
    if:
      - promotion in ['Freeleech!'] and leechers|int > 10 and seeders|int >0: accept
    qbittorrent_mod:
      action:
        add:
          reject_on:
            dl_speed: 0.8
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template

  rss_download:
    inputs:
      - rss:
          url: https://pterclub.com/torrentrss.php?rows=10&tag_internal=yes&isize=1&linktype=dl&passkey=xxxxxxxx
          all_entries: no
      - rss:
          url: https://www.skyey2.com/ptrss.php?id=xxxxxxxx
          all_entries: no
      - rss:
          url: https://ourbits.club/torrentrss.php?rows=10&tea1=1&isize=1&passkey=xxxxxxxx&https=1&linktype=dl
          all_entries: no
      - rss:
          url: https://chdbits.co/torrentrss.php?rows=10&tea14=1&tea13=1&tea1=1&isize=1&linktype=dl&passkey=xxxxxxxx
          all_entries: no
      - rss:
          url: https://pt.keepfrds.com/torrentrss.php?rows=10&tea6=1&tea3=1&tea8=1&tea9=1&tea10=1&isize=1&linktype=dl&passkey=xxxxxxxx
          all_entries: no
      - rss:
          url: https://www.tjupt.org/torrentrss.php?rows=10&official=1&passkey=xxxxxxxx&linktype=dl
          all_entries: no
      - rss:
          url: https://pt.m-team.cc/torrentrss.php?https=1&rows=10&tea9=1&isize=1&linktype=dl&passkey=xxxxxxxx
          all_entries: no
      - rss:
          url: https://hdsky.me/torrentrss.php?rows=10&tea6=1&tea1=1&tea28=1&tea9=1&tea31=1&tea18=1&tea22=1&tea34=1&tea35=1&isize=1&linktype=dl&passkey=xxxxxxxx
          all_entries: no
    no_entries_ok: yes
    accept_all: yes
    limit_new: 1
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template

  reseed:
    priority: 1
    plugin_priority:
      from_qbittorrent_mod: 250
      iyuu_auto_reseed: 240
    iyuu_auto_reseed:
      iyuu: 'xxxxxxxx'
      passkeys:
        1ptba: 'xxxxxxxx'
        52pt: 'xxxxxxxx'
        beitai: 'xxxxxxxx'
        btschool: 'xxxxxxxx'
        ccfbits: 'xxxxxxxx'
        chdbits: 'xxxxxxxx'
        dicmusic:
          authkey: 'xxxxxxxx'
          torrent_pass: 'xxxxxxxx'
        discfan: 'xxxxxxxx'
        dmhy: 'xxxxxxxx'
        eastgame: 'xxxxxxxx'
        et8: 'xxxxxxxx'
        haidan: 'xxxxxxxx'
        hd: 'xxxxxxxx'
        hd-torrents: 'xxxxxxxx'
        hd4fans: 'xxxxxxxx'
        hdarea: 'xxxxxxxx'
        hdbd: 'xxxxxxxx'
        hdcity:
          headers:
            cookie: 'xxxxxxxx'
            user-agent: '{? headers.user_agent ?}'
        hdchina:
          headers:
            cookie: 'xxxxxxxx'
            user-agent: '{? headers.user_agent ?}'
        hddisk: 'xxxxxxxx'
        hddolby: 'xxxxxxxx'
        hdfans: 'xxxxxxxx'
        hdhome: 'xxxxxxxx'
        hdsky:
          headers:
            cookie: 'xxxxxxxx'
            user-agent: '{? headers.user_agent ?}'
        hdstreet: 'xxxxxxxx'
        hdtime: 'xxxxxxxx'
        hdupt: 'xxxxxxxx'
        hdzone: 'xxxxxxxx'
        hitpt: 'xxxxxxxx'
        joyhd: 'xxxxxxxx'
        keepfrds: 'xxxxxxxx'
        lemonhd: 'xxxxxxxx'
        msg: 'xxxxxxxx'
        m-team: 'xxxxxxxx'
        nicept: 'xxxxxxxx'
        nanyangpt: 'xxxxxxxx'
        open: 'xxxxxxxx'
        oshen: 'xxxxxxxx'
        ourbits: 'xxxxxxxx'
        pterclub: 'xxxxxxxx'
        pthome: 'xxxxxxxx'
        ptsbao: 'xxxxxxxx'
        pttime: 'xxxxxxxx'
        skyeysnow: 'xxxxxxxx'
        soulvoice: 'xxxxxxxx'
        springsunday: 'xxxxxxxx'
        sjtu: 'xxxxxxxx'
        tjupt: 'xxxxxxxx'
        totheglory: 'xxxxxxxx'
        yingk: 'xxxxxxxx'
    accept_all: yes
    no_entries_ok: yes
    seen:
      fields:
        - url
    qbittorrent_mod:
      action:
        add:
          skip_checking: yes
          reject_on:
            dl_speed: no
            dl_limit: no
    template:
      - qbittorrent_base_template
      - qbittorrent_add_template
      - from_qbittorrent_template

  resume:
    priority: 2
    disable: [ seen, seen_info_hash, retry_failed ]
    if:
      - qbittorrent_state == 'pausedUP' and qbittorrent_downloaded == 0 and qbittorrent_added_on > now - timedelta(hours=1): accept
    template:
      - from_qbittorrent_template
      - qbittorrent_base_template
      - qbittorrent_resume_template

  delete:
    priority: 3
    disable: [ seen, seen_info_hash, retry_failed ]
    if:
      - qbittorrent_category in ['Rss'] and qbittorrent_last_activity < now - timedelta(hours=1): accept
      - qbittorrent_state == 'missingFiles' or (qbittorrent_state in ['pausedDL'] and qbittorrent_completed == 0): accept
      - "'open' in qbittorrent_tags and (qbittorrent_seeding_time < 48*60*60 or qbittorrent_num_complete < 5)": reject
      - "'gazellegames' in qbittorrent_tags and qbittorrent_seeding_time < 80*60*60": reject
    sort_by: qbittorrent_reseed_last_activity
    template:
      - from_qbittorrent_template
      - qbittorrent_base_template
      - qbittorrent_delete_keeper_template

  modify:
    priority: 4
    disable: [ seen, seen_info_hash, retry_failed ]
    accept_all: yes
    template:
      - from_qbittorrent_template
      - qbittorrent_base_template
      - qbittorrent_modify_template

  clean:
    priority: 5
    disable: [ seen, seen_info_hash, retry_failed ]
    regexp:
      accept:
        - '[Tt]orrent not registered with this tracker'
        - 'Torrent banned'
        - 'Unregistered torrent'
      from: qbittorrent_tracker_msg
    template:
      - from_qbittorrent_template
      - qbittorrent_base_template
      - qbittorrent_delete_cleaner_template

  manage_conn:
    disable: [ seen, seen_info_hash, retry_failed ]
    from_qbittorrent_mod:
      server_state: yes
    accept_all: yes
    if:
      - 'server_state["queued_io_jobs"] < 20':
          set:
            step: 50
      - 'server_state["queued_io_jobs"] > 80':
          set:
            step: -100
    template:
      - from_qbittorrent_template
      - qbittorrent_base_template
      - qbittorrent_manage_conn_template

  sign_in:
    auto_sign_in:
      user-agent: '{? headers.user_agent ?}'
      max_workers: 1
      aipocr:
        app_id: 'xxxxxxxx'
        api_key: 'xxxxxxxx'
        secret_key: 'xxxxxxxx'
      sites:
        qbittorrent:
          - name: qbittorrent
            host: qbittorrent.example.com
            port: 443
            use_ssl: yes
            username: admin
            password: xxxxxxxx
          - name: qbittorrent2
            host: qbittorrent2.example.com
            port: 443
            use_ssl: yes
            username: admin
            password: xxxxxxxx
        1ptba: 'xxxxxxxx'
        52pt: 'xxxxxxxx'
        avgv: 'xxxxxxxx'
        beitai: 'xxxxxxxx'
        btschool: 'xxxxxxxx'
        ccfbits: 'xxxxxxxx'
        chdbits: 'xxxxxxxx'
        dhcmusic: 'xxxxxxxx'
        dicmusic: 'xxxxxxxx'
        discfan: 'xxxxxxxx'
        dmhy:
          cookie: 'xxxxxxxx'
          username: 'xxxxxxxx'
          comment: 'xxxxxxxx'
          ocr_config:
            retry: 15
            char_count: 3
            score: 40
        eastgame: 'xxxxxxxx'
        et8: 'xxxxxxxx'
        filelist: 'xxxxxxxx'
        gazellegames: 'xxxxxxxx'
        hd: 'xxxxxxxx'
        haidan: 'xxxxxxxx'
        hd-torrents: 'xxxxxxxx'
        hd4fans: 'xxxxxxxx'
        hdarea: 'xxxxxxxx'
        hdatmos: 'xxxxxxxx'
        hdbd: 'xxxxxxxx'
        hdchina: 'xxxxxxxx'
        hdcity: 'xxxxxxxx'
        hddolby: 'xxxxxxxx'
        hddisk: 'xxxxxxxx'
        hdfans: 'xxxxxxxx'
        hdhome: 'xxxxxxxx'
        hdpost:
          login:
            usernameOrEmail: 'xxxxxxxx'
            password: 'xxxxxxxx'
        hdsky: 'xxxxxxxx'
        #hdstreet: 'xxxxxxxx'
        hdtime: 'xxxxxxxx'
        hdupt: 'xxxxxxxx'
        hdzone: 'xxxxxxxx'
        hitpt: 'xxxxxxxx'
        htpt: 'xxxxxxxx'
        joyhd: 'xxxxxxxx'
        jptv: 'xxxxxxxx'
        keepfrds: 'xxxxxxxx'
        lbj007: 'xxxxxxxx'
        lemonhd: 'xxxxxxxx'
        m-team:
          login:
            username: 'xxxxxxxx'
            password: 'xxxxxxxx'
            secret_key: 'xxxxxxxx'
        msg: 'xxxxxxxx'
        nicept: 'xxxxxxxx'
        nanyangpt: 'xxxxxxxx'
        open: 'xxxxxxxx'
        oshen: 'xxxxxxxx'
        ourbits:
          login:
            username: 'xxxxxxxx'
            password: 'xxxxxxxx'
        pterclub: 'xxxxxxxx'
        pthome: 'xxxxxxxx'
        pttime: 'xxxxxxxx'
        ptsbao: 'xxxxxxxx'
        skyey2:
          login:
            username: 'xxxxxxxx'
            password: 'xxxxxxxx'
        soulvoice: 'xxxxxxxx'
        springsunday: 'xxxxxxxx'
        sjtu: 'xxxxxxxx'
        torrentleech: 'xxxxxxxx'
        totheglory: 'xxxxxxxx'
        tjupt: 'xxxxxxxx'
        wenyuan: 'xxxxxxxx'
        yingk: 'xxxxxxxx'
    accept_all: yes
    seen:
      fields:
        - title
    notify:
      task:
        always_send: false
        message: |+
          {%- if task.accepted -%}
          {%- for group in task.accepted|groupby('task') -%}
          FlexGet has just signed in {{ group.list|length }} sites for task {{ group.grouper }}:
          {%- for entry in group.list %}
          {{ loop.index }}: {{ entry.title }} {{ entry.result }}
          {%- endfor -%}
          {%- endfor -%}
          {%- endif -%}
          {%- if task.failed %}
          {% for group in task.failed|groupby('task') %}
          The following sites have failed for task {{ group.grouper }}:
          {%- for entry in group.list %}
          {{ loop.index }}: {{ entry.title }} {{ entry.result }} Reason: {{entry.reason|d('unknown')}}
          {%- endfor -%}
          {%- endfor -%}
          {%- endif -%}
          {%- for group in task.entries|groupby('task') %}
          {% for entry in group.list %}
          {%- if entry.messages|d('') %}
          Messages:
          {{ entry.title }} {{ entry.messages }}
          {% endif %}
          {%- endfor -%}
          {%- endfor -%}
        via:
          - wecom:
              corp_id: 'xxxxxxxx'
              corp_secret: 'xxxxxxxx'
              agent_id: 'xxxxxxxx'
              to_user: 'xxxxxxxx'
              image: 'details_report.png'
          - telegram:
              bot_token: 'xxxxxxxx'
              recipients:
                - username: 'xxxxxxxx'

  warner:
    disable: [ seen, seen_info_hash, retry_failed ]
    from_qbittorrent_mod:
      server_state: yes
    if:
      - 'not server_state["flexget_connected"]': accept
      - 'server_state["dl_info_speed"] < 1048576': accept
      - 'server_state["up_info_speed"] < 1048576': accept
      - 'server_state["free_space_on_disk"] < 5368709120': accept
    template:
      - from_qbittorrent_template
    notify:
      entries:
        message: |+
          {{ time }}
          qBittorrent Server State:
          {% if not server_state.flexget_connected -%}
          flexget_connected: False
          {%- else -%}
          dl_info_speed: {{(server_state['dl_info_speed']/1024/1024)|int}} MiB
          up_info_speed: {{(server_state['up_info_speed']/1024/1024)|int}} MiB
          free_space_on_disk: {{(server_state['free_space_on_disk']/1024/1024/1024)|int}} GiB
          {% endif %}
        via: *via_setting